# SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
# FROM DEVELOPERS
# WHERE
# SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')
# OR
# SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')
# ORDER BY ID;

# JOIN 사용
# SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
# FROM DEVELOPERS D JOIN SKILLCODES S ON D.SKILL_CODE & S.CODE > 0
# WHERE S.NAME IN ('Python', 'C#')
# ORDER BY D.ID;

# IN SUM 사용
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (
    SELECT SUM(CODE)
    FROM SKILLCODES
    WHERE NAME IN ('Python', 'C#')
) > 0
ORDER BY ID;