# IN
# SELECT COUNT(*) AS FISH_COUNT
# FROM FISH_INFO
# WHERE FISH_TYPE IN (
#     SELECT FISH_TYPE FROM FISH_NAME_INFO WHERE FISH_NAME IN ('BASS', 'SNAPPER')
# )

# JOIN
SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO FI JOIN FISH_NAME_INFO FN ON FI.FISH_TYPE = FN.FISH_TYPE
WHERE FN.FISH_NAME IN ('BASS', 'SNAPPER');

# EXISTS
# SELECT COUNT(*) AS FISH_COUNT
# FROM FISH_INFO FI
# WHERE EXISTS (
#     SELECT 1
#     FROM FISH_NAME_INFO FN
#     WHERE FI.FISH_TYPE = FN.FISH_TYPE
#       AND FN.FISH_NAME IN ('BASS', 'SNAPPER')
# );